import type { ScanReport } from './scan';

/**
 * Renders `content/REVIEW_QUEUE.md` from a scan (§10 Phase 4 acceptance:
 * "REVIEW_QUEUE.md auto-generated").
 *
 * The non-code dependency table at the bottom is *not* generated — those are
 * long-lead human commitments (find a pandit, book a studio), not facts
 * derivable from the files, so the generator preserves whatever is written
 * there rather than overwriting a human's status updates.
 */

export const GENERATED_MARKER = '<!-- BEGIN GENERATED: placeholders -->';
export const GENERATED_END = '<!-- END GENERATED -->';

const HEADER = `# Content review queue

Every ritual string in this repo is **data authored or approved by a named
pandit**, never invented by an engineer or a model (§0.3, §0.4). This file is
the running list of everything still waiting on that review.

## How to use it

- When you add content you cannot source, write the placeholder
  \`"⟨TODO_PANDIT: some_id⟩"\` in the JSON — it appears below automatically.
- When a pandit approves a file, set its
  \`review: { status: "APPROVED", reviewer, date }\` block and re-run the build.
- **Gate (Phase 10): the table below must be empty and every content file
  \`APPROVED\` before a production release.**

> The placeholder section below is generated by \`pnpm content:build\`.
> Do not edit it by hand — edit the content, then re-run the build.
`;

/**
 * How many placeholder ids to name per file before summarising the rest.
 *
 * An enum file has hundreds — listing every one turns the table into an
 * unreadable wall and buries the files that have a handful of real gaps. A
 * few examples plus the count is what a reviewer actually needs to triage;
 * the file itself is the authoritative list.
 */
const MAX_IDS_SHOWN = 6;

function summarise(report: ScanReport): string {
  const withPlaceholders = report.files.filter((f) => f.placeholders.length > 0);

  if (report.totalPlaceholders === 0) {
    return '\n_No `⟨TODO_PANDIT: …⟩` placeholders remain._\n';
  }

  const rows = withPlaceholders
    .map((file) => {
      const shown = file.placeholders.slice(0, MAX_IDS_SHOWN).map((p) => `\`${p.id}\``);
      const remaining = file.placeholders.length - shown.length;
      const ids = remaining > 0 ? `${shown.join(', ')}, … +${remaining} more` : shown.join(', ');
      return `| \`${file.file}\` | ${file.placeholders.length} | ${ids} |`;
    })
    .join('\n');

  return `
**${report.totalPlaceholders} placeholder${report.totalPlaceholders === 1 ? '' : 's'}** across ${withPlaceholders.length} file${withPlaceholders.length === 1 ? '' : 's'}.

| File | Count | Placeholder ids |
| ---- | ----- | --------------- |
${rows}
`;
}

function reviewStatusTable(report: ScanReport): string {
  const rows = report.files
    .filter((file) => file.reviewStatus !== null)
    .map((file) => {
      const status =
        file.reviewStatus === 'APPROVED'
          ? `✅ approved${file.reviewer ? ` by ${file.reviewer}` : ''}`
          : '⬜ pending';
      return `| \`${file.file}\` | ${status} |`;
    })
    .join('\n');

  return `
### File review status

| File | Status |
| ---- | ------ |
${rows}
`;
}

/**
 * Builds the full REVIEW_QUEUE.md, preserving the hand-maintained
 * "Non-code dependencies" section from the existing file if there is one.
 */
export function renderReviewQueue(report: ScanReport, existing: string | null): string {
  const generated = `${HEADER}
## Open items

${GENERATED_MARKER}
${summarise(report)}${reviewStatusTable(report)}
${GENERATED_END}
`;

  const tail = existing ? extractNonCodeSection(existing) : null;
  return tail ? `${generated}\n${tail}` : generated;
}

/** The hand-written section after the generated block, if the file has one. */
function extractNonCodeSection(existing: string): string | null {
  const marker = '## Non-code dependencies';
  const index = existing.indexOf(marker);
  return index === -1 ? null : existing.slice(index).trimEnd() + '\n';
}
